hash-format = "sha256"

[[files]]
file = "mods/add-on-the-abyss-beginning.pw.toml"
hash = "86ec24414dfb457eca90bb8879c566c7dfdd8064bea0703327b09450774dc8eb"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "59c031acd428bb40e6fbf42300f5b7f6f43cbe99c03c421539b0af065cb90080"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "aa8adc794cf6f3d5b641a1fcea9f5a2b7028009f19b226ce14160dd971c48993"
metafile = true

[[files]]
file = "mods/angel-ring.pw.toml"
hash = "665594215dbdc74b86a71c1943a9b414af9ff6df11b4f7ef6045956d8ba33ffe"
metafile = true

[[files]]
file = "mods/antique-atlas.pw.toml"
hash = "e51dbbcf20abd0284270043ae5df4e4f3712442ff23cfee22013b26303b71522"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "1c0b0019300b6e06e87249b0f8843dbc6a0ed19e0c679320c69dda9775b7740f"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "725fb099daedadf39a6596de0bae947e98168a995f8e7e8ce3b70ee0b9e5a0f7"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "3ef39814eff961d73203456044854e801f8f1f3447bdf5b6fa3c1c26d234ce18"
metafile = true

[[files]]
file = "mods/areas.pw.toml"
hash = "d6c3cfacd037d8c774f0c67fd840057217fa7f35042b1d67d444e21012017262"
metafile = true

[[files]]
file = "mods/ars-arsenal.pw.toml"
hash = "1580f40932d6349d2b438eeeb34602e6becf621f697ee7a962eeed9757475867"
metafile = true

[[files]]
file = "mods/ars-elemental.pw.toml"
hash = "00d63f3e7e810a58bc9180c190ca497d85e00a4933888f6953ab41feb066ebba"
metafile = true

[[files]]
file = "mods/ars-enderstorage.pw.toml"
hash = "ef2de516ed2060b20ac22d20532d80eb8b417e86c9fbd02ee863bf3f043094c7"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "9a116738043fb2ffffef1ee31556033bd7f2fdf37a7e1c4a7f77a5ac9bb62031"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "fca21ba2e8935773ce2dee899109caee7851fa98b1e72e927bf0dc7b3f599430"
metafile = true

[[files]]
file = "mods/astral-sorcery.pw.toml"
hash = "3b42dd42c124325a194e8784f2658dc5d3aebf6fe20da393ac76e0eef098a38d"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "9b2088287d126347cb44a539b7104462e0a4aaa0b871577ca13902398f174f52"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "33fef2ac176ffb172524907c4416dfb97c84c0418288ceb6cd735064113fb66d"
metafile = true

[[files]]
file = "mods/betternether-reforged.pw.toml"
hash = "93db0d9a8538c2e302afa9f52c6efab4e3460cc33a398c101dffa2d0ebd3574a"
metafile = true

[[files]]
file = "mods/biggerreactors.pw.toml"
hash = "a141da5784fc34982b38a07a768fc9fb2e368a576b6dfe4df9dfe9496d541fef"
metafile = true

[[files]]
file = "mods/biomancy.pw.toml"
hash = "ab7bb709a84fefbcac213a95f097621cca050e8168ee51445acf2435a9f24530"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "f06255716712432059cdbfef6618fd7f33b8d9521563d8c0705f138a422b5030"
metafile = true

[[files]]
file = "mods/blood-magic.pw.toml"
hash = "12892f588a6b194af62f65a02d455ad6cb62715e11a7cb04f2b5291ca7b1c840"
metafile = true

[[files]]
file = "mods/blue-skies.pw.toml"
hash = "956c4c9554aa266e61a9635d05d1dcf85a536349a3f8e1e3d5f8c96c94c08533"
metafile = true

[[files]]
file = "mods/born-in-chaos.pw.toml"
hash = "f59e8e948f2e5821d36bc42a15c2a67261907a6a0f7e5d44fcd4dbf232692a63"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "7e0af47e33a6ccae31697552c1d1ff0158a68b8507daa0f030775c0cbdb4b4f4"
metafile = true

[[files]]
file = "mods/bountiful.pw.toml"
hash = "8f7855046d9a88e7b97be1eb8c35ac5c79f4dc86b2d2c813a55248255d34e73c"
metafile = true

[[files]]
file = "mods/brandons-core.pw.toml"
hash = "be54c9fa4c167693d9937b652602ba3d8481af053d759915d8b211fbcfc76c61"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "0542b0b4cf6a1406c6325971787095ad4e4bcfefe1ad106e7c6d0db2fdbab401"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "35cd0b72092f5423d6430cc8aa37c182dbf01edfe42bc8785819779fc3d6f16d"
metafile = true

[[files]]
file = "mods/cb-compressed-blocks.pw.toml"
hash = "ea0193f6dcd9c745d87e7ec4918aa9a581dde2735b7d05c82c8bd363c89173e0"
metafile = true

[[files]]
file = "mods/champions.pw.toml"
hash = "2d98a2fbe0ad0de8922e7abf448d964d02a3c7a1a3eec8bfc2b26b9e47dc49b2"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
hash = "a879bc85f06bd961fe1d27c758ae8a7e7886d51905f2a0a61934e6697c6954f3"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "02d3751895e1aea3675afb6d16424e4dcefdcf8c3fe9c486fda53b250e624ced"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "67a32a2480285afa9bd3bab47fc674a2cca4434db092e69949476750b02a6074"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "c26308548643945934745be773754649df081cd5163b90f1f805a7eced96e1f8"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "1e95c8b5e4154d24345875c263488989d8222e24065ab21cde7aaf145e750e2b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "a5af19c3b7903d7891f6afb804d923e3bd699b49c102580ea60c996b11977ee7"
metafile = true

[[files]]
file = "mods/combat-commons.pw.toml"
hash = "987c79a2ddc14a193382cc3501bc84a90689ca2d4b9a76c24f805ef356043982"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
hash = "43c3d098af2f3f60ede43808d64ddeb057a019ae91096c144a3c9ea80d330bb2"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "736dbe1ea51b7798b21045657291f02b530875fd94b98c084de4acedc9999f2b"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
hash = "b21b4164982bac91457200c78d38981a823eac8756f64f396fb22dbf42abc1a4"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "ee6b63b9f81d87c75ac5115232548df5347fe9456f7ee8a80cd137043616191a"
metafile = true

[[files]]
file = "mods/creeperhost-presents-soul-shards.pw.toml"
hash = "ae87e2f26de6556bbf538512639f796673818bb98b8cbd9af6ee504b03b07526"
metafile = true

[[files]]
file = "mods/cucumber.pw.toml"
hash = "3f224b17c8bb8d913ae1acd3ae272d8a8b73d565523b5da5af7d85b4780fea10"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1da259efe44c59b295ce121e4a5779a8de5b893de673db071fd8b5132d09a022"
metafile = true

[[files]]
file = "mods/draconic-evolution.pw.toml"
hash = "207aed7f36f7cff25ba7d3de546b3351b6e3cfaed26ef3c5b14aeca6f419285d"
metafile = true

[[files]]
file = "mods/druidcraft.pw.toml"
hash = "871b0cb97b3833d60734c71bbd069a521e009a1b97d7595138cd9ce34a9979ae"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "aa7791567710f5ed615f4bcc513a65ac80807982996408e7a3c281f4a2bc5a56"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "9a8c4e1f33f6f5349e7fd841734fa1db255a9a2e531cfc35c43163da3986ea87"
metafile = true

[[files]]
file = "mods/enhanced-celestials.pw.toml"
hash = "9f30d14b387622c56f7411f68726609b14a1405ed3f9f1116e8f72a8e5b4f0b9"
metafile = true

[[files]]
file = "mods/essential-mod.pw.toml"
hash = "8d48d1779abf3b4eb5d70284491aaacbb2ddb297d008036885288af31b0626fb"
metafile = true

[[files]]
file = "mods/ex-nihilo-sequentia.pw.toml"
hash = "8f16863cda20bfe9da5ac1a3420f1b6919072558f0219833336bc01aa584efbf"
metafile = true

[[files]]
file = "mods/expandability.pw.toml"
hash = "856e791972a4705daba7d691290f81ed67a061e4850eb17bd6c9bb82b7b49e20"
metafile = true

[[files]]
file = "mods/extra-utilities-reborn.pw.toml"
hash = "286302d31e4dac780110d557c174db5ccad236d40b0a9b4c416c13672e3e3cea"
metafile = true

[[files]]
file = "mods/extrabotany.pw.toml"
hash = "e38fff8adee63958f6ff14a1d1a4fab47dce569d969d403747b1a1c1d2e0986c"
metafile = true

[[files]]
file = "mods/falling-leaves-forge.pw.toml"
hash = "2d85cf469f1424634eaf9dc649a1feb14c88692f701273b27505c3dd2742c09f"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "a424ec5b93294f8c1d51b21684233052965e6ee2b343213813599a031804e93f"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "0356009ae37c9c7eca5d839a021fbaca73de03480415fde73089e2c814873406"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "37b9b71a2ae4d1cae29c27830bbe809c36601f066f48fb71d822f98ad82d0c1e"
metafile = true

[[files]]
file = "mods/frosted-friends.pw.toml"
hash = "4efed8626f0ff07495aedddb228c128a86b09345a242dc022fa445e2ff37a05b"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "f1785b6fb4b3bd26594e173737a653a237f9e9e9c0d330faa56bdf0225217d75"
metafile = true

[[files]]
file = "mods/goblin-traders.pw.toml"
hash = "24871d7f43702c4656cdbbd65e0bc3ee04c3e901d6d5fa357078f964e609bb43"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "5d242849b481d8e19ba20dc1cbb56c8d91ca3f3466a7e77c9f7a52c6f96f09b2"
metafile = true

[[files]]
file = "mods/hats.pw.toml"
hash = "cbcf77694c822a81329e43413cc94e317701cb036068e4f6df6668ce2f3bfb6d"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "da8427f8dbe0bcc6f2dd87c7068874f5b37043ccfa2af5b0167c72fa288150da"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
hash = "66db052a77a41fb26a42ae5803d56a484ee4cae7f0a32561ec43c2afd2e84f13"
metafile = true

[[files]]
file = "mods/immersive-portals-for-forge.pw.toml"
hash = "fc26a2ef57457a03fdb5ae33bf499be96cb6b2a0b89c9bf0ea1251eb5d3bd826"
metafile = true

[[files]]
file = "mods/inventory-pets.pw.toml"
hash = "e3a5bea7026d119847f46252d68ca9333028aba1a6a2460cd5f28608b2745bbf"
metafile = true

[[files]]
file = "mods/inventory-sorter.pw.toml"
hash = "a5b21098863b296078f411aabe8699376f969c067375ffb2a254ee660f30f330"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "68995b9ea503260f1a5dafe4667b028fa44c3079d50c7372d85f842db274088e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "c7ec1444792e09cced117d3ad2d27f2c4d952dd1989b3110ef98c4970f228ab4"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "3aff473c4bf2e5133793d6028bc7c6de57359b20ebe83af08832a1eda08babd3"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "bc41332a54157c3753a817a7e4a2c77653bba74117d04f7d7d2345db6ca6ded1"
metafile = true

[[files]]
file = "mods/jumpy-boats.pw.toml"
hash = "0ff1e7ed0eab11a07cb3bafa7c553b406893cb0ceffd4dd6728f27219bf6829d"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "df69a98ee4cfa09c29e7702c2948007de9ad2e7c03d618c79d664a79cd6a6da1"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "101ccb175a05a5aed1fbd318cc4b0c7112a4dfd4315fa502de165dcb5b3eaeac"
metafile = true

[[files]]
file = "mods/l_ender-s-cataclysm.pw.toml"
hash = "7e6680eaf3af46acac0bcbd468f3490267e3c0d04a4f29f77cc32712cef55406"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.pw.toml"
hash = "4cbade87fef39ba34f9b459b8d238fa761901c4817db0564ef4dae1a06e4b832"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "f716234315da430480a4c8ddeef64291c86ebb8b3f5c316265517c000d73062c"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "7edc90a4c9d38b882798d87a444e87893597bcab46a9e5226c8f83d9515c895c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "9d3255b25a9f08112f6f18061a73c338189e396d3164942922ce25c613974fea"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "04a92a819f7c3dff89382baf5c5fb25c1386da08ead8510ea009aa1ccc8daf02"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "bc72a59c06f9128b3c0fd6983e87c64e12075708b047c218d79dafeb73dd70b1"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.pw.toml"
hash = "fe3b73d41512471f2e6a1587fe7ef07e7bd436fa9be27a22ac1f8d40443ba15e"
metafile = true

[[files]]
file = "mods/mutant-beasts.pw.toml"
hash = "cf02d880e3a8c5d5eaf3e0edd888ba22179f115f7818d3a09060fa4902d17bf1"
metafile = true

[[files]]
file = "mods/mystical-agradditions.pw.toml"
hash = "cf53f465b794bd203569f69f068fa3265d03fb612a00f69ac8f70d55507ece9a"
metafile = true

[[files]]
file = "mods/mystical-agriculture.pw.toml"
hash = "a7a51313e39f2dcc3bbfc2a9cc6b0920d25b7a39e989479787a6d4aed752d6e9"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "cca1d003d1f4ff138be6a04cedac1f97e1f4a85862d5958d97aed82e951a78ff"
metafile = true

[[files]]
file = "mods/nether-portal-spread.pw.toml"
hash = "4e7332903e246ca9067a4a0233768febee04bb0e0000dfa5a9013c24caf98e9a"
metafile = true

[[files]]
file = "mods/not-enough-crashes-forge.pw.toml"
hash = "93d9d65d11722a0a636670c01b11e25db92fc17b233686a50f7ccfac6aae2514"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "3d41dcd2e8fc986509671342451cc7b8fc0c8887820fa409161acade8248214c"
metafile = true

[[files]]
file = "mods/ob-aquamirae.pw.toml"
hash = "e041e00d5469efd2ad52d084da426c781ec13df532dce3cf1b9bedf30079b984"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "090b142f2ccd86265f8dc1d52c8d83f785aa9712bd088b11cd6cdf65ea6c1c98"
metafile = true

[[files]]
file = "mods/observerlib.pw.toml"
hash = "8a2ae2e0314307a913514d5447466e3a50cc00a78e936e4e6be4497a406afa56"
metafile = true

[[files]]
file = "mods/occultism.pw.toml"
hash = "be0db50a708431e4f656eb66da738e57f0cbea88069a7795abd33ba64536bc56"
metafile = true

[[files]]
file = "mods/oh-the-biomes-youll-go.pw.toml"
hash = "13c7d44940110bb9d8149f3e2403356e1fe33c1eece4a197bcb5835cdb1f3de4"
metafile = true

[[files]]
file = "mods/openblocks-elevator.pw.toml"
hash = "aab2419fe29a0b13b10ae0b71bb549f80d2e5e1541677c0982012c77711326f5"
metafile = true

[[files]]
file = "mods/ore-excavation.pw.toml"
hash = "99b6906f304e7c3548599ecf0becb1e0fea771eb4ab3d243b51a7ad434ec946d"
metafile = true

[[files]]
file = "mods/origins-forge.pw.toml"
hash = "d7605878a5a7cdb600d80b10b1dadb02b9ef7eef4c5b810898e50cde5a263261"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-core.pw.toml"
hash = "d718dbaf53f870c0746b71c20c070d550bc35753f4e5fe6661bfa760d01fb52e"
metafile = true

[[files]]
file = "mods/pandoras-box.pw.toml"
hash = "30bdf80316337b6a6a6d3a5a3708ebac0a011d1c1d514d6130661848f54bfeb8"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "adfaa4397b987d1589056f24fbe6c80d79c56a2a828d151c5a927c60d79a920a"
metafile = true

[[files]]
file = "mods/phosphophyllite.pw.toml"
hash = "aa785bb7471e70497ab115f1fbf1cc69297ff10bb1fc59b21dee5a5cca63ae3a"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8b80951a6a78f26b1e0ba54d1193cfc63743001fc4f105b30ca5bc4f67dcb05b"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "4437b60017c0598182f1c25a7b50dd201f34c7ea98de1876fb4617fc76cce69a"
metafile = true

[[files]]
file = "mods/random-village-names.pw.toml"
hash = "422ada06aee64496583f6a29028bb1f92978bcfd55c45ecb4cd2a9d676a68b3c"
metafile = true

[[files]]
file = "mods/rats.pw.toml"
hash = "c90ca086f3602640d4ec57c2d9633cda955193ad17ca0eba3ad2df9816e1f8ca"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
hash = "ded97547d477c8a436c3cb564e7abc9840876b89b0da9f1b828ef6dc17604f2f"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "8535b7291edee6587dda25932bfa92047a6ddc29d8d6490e4e974ca5b37ed89f"
metafile = true

[[files]]
file = "mods/shroom-dealers.pw.toml"
hash = "416c6d18dbd52ced97e84afe4417dc06f06212ad4acbedb98b0b8294179ac978"
metafile = true

[[files]]
file = "mods/silent-lib.pw.toml"
hash = "bf36e291f04b41423d233a327ac14841166374178c355e3d35cc47a1168411b7"
metafile = true

[[files]]
file = "mods/sit.pw.toml"
hash = "4ce44809ab2391253ed37032692ec47e85d6dc414552ac6f3efcb429f4e5c7b9"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "3f7bdf144b09082021c01cce53753e045f7d2077912057c4f547f3cfe5854e81"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "7b5c9093a8309bf016de0bd7bd655b6522632d6c8291c3cdeb9a27c327667311"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
hash = "dfdc3a2acb84cccc00c8cf27203019f5fcc9d10f9c9d0c524009f5094b19ccc0"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "c4f0f9a5c8b0d53f2cde0befb4d96a1af804f2eba849b20b4bf2df71f747e97c"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "88dd07c94961c665a7df7d663b494b3fbc4f6ee18e16ac61439b063cadb5ae5d"
metafile = true

[[files]]
file = "mods/the-abyss-chapter-ii.pw.toml"
hash = "1baf7add94f42b32b8305a4f5473c13d1744387312e7a4b321cba7ab6c318a10"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "9103343f6fb5d720f09ce45eee2ba77c892191b43082067da89be04d9fd25a60"
metafile = true

[[files]]
file = "mods/the-undergarden.pw.toml"
hash = "a11396ee6473345fff9ce1539f1897fa2b370faabe651f1536a1da0577277438"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
hash = "f312dfc5bc8805e77065dc2db25eebf2bd53f8c068d18c21952018cbbe82de77"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "068c5ac6f7be4330d30b6e298c94db4f28b084d854185b389370b6051b8b204b"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "1dda287b20d9afec27864e9625dc7c4017f66ece39e117c10dcd97edc42c68a3"
metafile = true

[[files]]
file = "mods/tome-of-blood.pw.toml"
hash = "f73302b6df8ab6a376dc35d4c9b14606c6b36a2e85c4eb133ddb721301078ca0"
metafile = true

[[files]]
file = "mods/too-many-glyphs.pw.toml"
hash = "ea3b384a685009452c703dc55ca6c6342c79b423c5d870568a454f4f1c5c57ea"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
hash = "5e6e4d187bdc9105fc152c4e5f3f46833c577a3147a83bf2155df8d4c0e9d096"
metafile = true

[[files]]
file = "mods/treasure-bags.pw.toml"
hash = "2a0b25ac9967d2f9b1e28901d46bae8e262f39a34b2440329286a0b938d4f392"
metafile = true

[[files]]
file = "mods/village-spawn-point.pw.toml"
hash = "1347294f5e7f5df0720783f5a29dfe6f395f5a64e6c316ad96c63a0b8c448551"
metafile = true

[[files]]
file = "mods/wall-jump.pw.toml"
hash = "5f7bc5a5b2e53fb4efee87fc2133558f488475fd80a8659980d124978b7f1f15"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "4931c4e65980ea1a95a61b35b18e7e893d59befce9c0764c387aa7773c44b15f"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d3631df0e5d46e75045a781efe2eda7ccbadc70c775dea298f6f5516e4f4dd74"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "def6e1aeb1416c41503a391973b9fde650eda84204178f90a99faa89fe9bfb83"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "ad6234ad0771472bd5bf582a5ddd737d9cb55fd6f364397eae3940b10574342d"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "8202f215a2400426059f5f9f488ef8a842d01d39000580c51581eb240549e276"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "5b83ab5539365be913d72985d9318c4f4b3cb39f074b8faa5c2180658258b363"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "a71342e2c54d9ec3ff4634118ac7e978c65a8bfdcee93f51ddbc4f0a5780dd62"
metafile = true
